export const demoTransactions = (userEmail) => [
    { type: 'income', category: 'salary', amount: 50000, date: new Date().toISOString(), description: 'Monthly Salary', email: userEmail },
    { type: 'expense', category: 'rent', amount: 15000, date: new Date().toISOString(), description: 'House Rent', email: userEmail },
    { type: 'expense', category: 'food', amount: 5000, date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(), description: 'Grocery Shopping', email: userEmail },
    { type: 'expense', category: 'transport', amount: 200, date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), description: 'Uber Ride', email: userEmail },
    { type: 'expense', category: 'transport', amount: 2000, date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(), description: 'Monthly Fuel', email: userEmail },
    { type: 'expense', category: 'utilities', amount: 3500, date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(), description: 'Electricity Bill', email: userEmail },
    { type: 'expense', category: 'utilities', amount: 1200, date: new Date(new Date().setDate(new Date().getDate() - 11)).toISOString(), description: 'Internet Bill', email: userEmail },
    { type: 'expense', category: 'entertainment', amount: 2500, date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(), description: 'Weekend Movie & Dinner', email: userEmail },
    { type: 'income', category: 'freelance', amount: 12000, date: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString(), description: 'Web Dev Project', email: userEmail },
    { type: 'receivable', category: 'loan', amount: 10000, date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(), description: 'Lent to Friend', personName: 'Rahim', email: userEmail },
    { type: 'payable', category: 'loan', amount: 5000, date: new Date(new Date().setDate(new Date().getDate() - 12)).toISOString(), description: 'Borrowed from Brother', personName: 'Karim', email: userEmail },
    { type: 'expense', category: 'health', amount: 1500, date: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(), description: 'Medicine', email: userEmail },
    { type: 'expense', category: 'education', amount: 4000, date: new Date(new Date().setDate(new Date().getDate() - 25)).toISOString(), description: 'Online Course', email: userEmail },
    { type: 'income', category: 'gift', amount: 2000, date: new Date(new Date().setDate(new Date().getDate() - 28)).toISOString(), description: 'Birthday Gift', email: userEmail },
    { type: 'expense', category: 'shopping', amount: 8500, date: new Date(new Date().setDate(new Date().getDate() - 18)).toISOString(), description: 'New Clothes', email: userEmail },
    { type: 'expense', category: 'food', amount: 450, date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(), description: 'Lunch', email: userEmail },
    { type: 'expense', category: 'food', amount: 320, date: new Date().toISOString(), description: 'Snacks', email: userEmail },
    { type: 'receivable', category: 'freelance', amount: 5000, date: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(), description: 'Pending Payment', personName: 'Client X', email: userEmail },
    { type: 'expense', category: 'subscriptions', amount: 900, date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(), description: 'Netflix & Spotify', email: userEmail },
    { type: 'expense', category: 'others', amount: 1000, date: new Date(new Date().setDate(new Date().getDate() - 8)).toISOString(), description: 'Donation', email: userEmail },
    { type: 'income', category: 'investment', amount: 3000, date: new Date(new Date().setDate(new Date().getDate() - 35)).toISOString(), description: 'Stock Dividend', email: userEmail },
];
